apiVersion: apps/v1

kind: Deployment

metadata:
  name: node-app

  labels:
    app: node-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: node-app

  template:
    metadata:
      labels:
        app: node-app

    spec:
      containers:
      - name: node-app
        image: YOUR_DOCKER_HUB/node-app:v1
        resources:


        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-pg-secret
        volumeMounts:
          - mountPath: "/root/.aws"
            name: aws-credentials
      volumes:
        - name: aws-credentials
          configMap:
            name: aws-credentials